version: "3.1"
services:

    webserver:
      image: nginx:alpine
      container_name: meetingDoctors-webserver
      working_dir: /meetingDoctors
      volumes:
          - .:/meetingDoctors
          - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      ports:
        - "8090:80"
      links:
        - php-fpm

    php-fpm:
      build: ./docker/php-fpm
      container_name: meetingDoctors-php-fpm
      working_dir: /meetingDoctors
      volumes:
        - .:/meetingDoctors
        - ./docker/php-fpm/php-ini-overrides.ini:/etc/php/7.2/fpm/conf.d/99-overrides.ini

    meetingDoctors:
      image: abh1nav/dockerui
      volumes:
          - /var/run/docker.sock:/var/run/docker.sock
      links:
          - webserver